services:  
  namenode:
    image: apache/hadoop:3.3.6
    container_name: namenode
    hostname: namenode
    user: "root"
    ports:
      - "9870:9870" # nameNode Web UI
      - "9000:9000" # HDFS IPC Port (for spark's connection)
    volumes:
      - ./namenode:/opt/hadoop/dfs/name
      # mount config
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    networks:
      - shared_network
    # auto format NameNode in the first run if folder is empty
    command: >
      bash -c "
      mkdir -p /opt/hadoop/dfs/name;
      if [ ! -d /opt/hadoop/dfs/name/current ]; then
        echo 'Formatting NameNode...';
        /opt/hadoop/bin/hdfs namenode -format -force -nonInteractive;
      fi;
      /opt/hadoop/bin/hdfs namenode
      "

  datanode:
    image: apache/hadoop:3.3.6
    container_name: datanode
    hostname: datanode
    user: "root"
    depends_on:
      - namenode
    ports:
      - "9864:9864" # dataNode Web UI
    volumes:
      - ./datanode:/opt/hadoop/dfs/data
      # mount cấu hình
      - ./conf/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./conf/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    networks:
      - shared_network
    command: >
      bash -c "
      mkdir -p /opt/hadoop/dfs/data;
      /opt/hadoop/bin/hdfs datanode
      "

networks:
  shared_network:
    external: true
